### ISSUE TITLE
Invalid short arguments

### ISSUE THREAD

**Issue by dguest** [lukedeo/option-parser#5]
Hi, I thought this would be a good drop in replacement for the boost option parser, but I must be doing something wrong because despite [what looks like an ok setup][1] I'm having issues.

The first was that the parser trims all the `-` out of the options. I would have expected that `--file-name` would become `file-name` but it gets shortened to `filename` instead. I was able to work around this [by hacking the `remove_character` function][2], but now I'm having a new problem. Specifically, I call my executable with

```
./thing -i input_file -o output_file
```

Where the `-i` flag [is defined as][3]

```C++
  opt.add_option("--in-file", "-i")
    .help("input file name").required(true)
    .mode(optionparser::store_value);
```

and [accessed as][4]

```C++
 files.in = opt.get_value<std::string>("in-file");
```

It seems like this should work, but I'm getting

```
In excecutable './thing':
Invalid flag '-i'
```

(it was also segfaulting when I used `opt.add_option("-i", "--in-file")`, but specifying the options in the wrong order was my mistake)

Should this work?

[1]: https://github.com/dguest/ttree2hdf5/blob/b70160ce0d37fdecfc454d45cd019daf00729b55/src/tree_copy_opts.cxx#L18-L56
[2]: https://github.com/dguest/ttree2hdf5/blob/b70160ce0d37fdecfc454d45cd019daf00729b55/include/parser.hh#L641-L648
[3]: https://github.com/dguest/ttree2hdf5/blob/b70160ce0d37fdecfc454d45cd019daf00729b55/src/tree_copy_opts.cxx#L21
[4]: https://github.com/dguest/ttree2hdf5/blob/b70160ce0d37fdecfc454d45cd019daf00729b55/src/tree_copy_opts.cxx#L46

**Comment by lukedeo** [comment]
hey @dguest just saw this, did you find a work around or have any insights into what was breaking?

**Comment by lukedeo** [comment]
hey @dguest wanted to see if you had any workarounds / PR potential here

**Comment by dguest** [comment]
Hey @lukedeo, yeah sorry for the slow reply.

I was thinking to use this as lightweight alternative to boost `program_options` (why, when almost all of boost is header-only, do I need to link to `program_options`?), but I ended up just fixing my CMake file. So I sort of gave up, sorry for not being more helpful.

**Comment by ntsvetanov** [comment]
Hello!

@lukedeo I think i have managed to solve two problems- dependency of argument order(
it was mandatory to be in long / short order) and I removed the deletion of dashes in whole argument name.
Also I have added testing framework [doctest](https://github.com/onqtam/doctest) and gitignore file.

p.s It is my first pull request :)
