### ISSUE TITLE
positional args

### ISSUE THREAD

**Issue by ntsvetanov** [lukedeo/option-parser#7]
Hey @lukedeo, 

thanks for merging my pull request! 

If you dont mind, I will try to implement positional arguments functionality.

**Comment by lukedeo** [comment]
@ntsvetanov awesome!

**Comment by lukedeo** [comment]
Hi @ntsvetanov if you end up trying to do positional arguments, ensure you do a quick refresh to `master`!

Hope you can figure out how to do positional args! 🤞

**Comment by lukedeo** [comment]
Hey @ntsvetanov just wanted to see if you are planning on trying to take this on or not! Thanks!

**Comment by ntsvetanov** [comment]
I will do it next few days

**Comment by lukedeo** [comment]
Hey @ntsvetanov wanted to see if you ever got around to this (no pressure)

**Comment by ntsvetanov** [comment]
Soon I will, sorry for delay :)

**Comment by ntsvetanov** [comment]
@lukedeo Once again sorry for delay. Ive made pull request. If you are happy with it next few days i can make some refactoring of the code and tests. Also i will add some more tests  :)

**Comment by lukedeo** [comment]
It's looking great @ntsvetanov! Let me know once the history is fixed up :) I've cloned your branch and am playing around with it.

**Comment by ntsvetanov** [comment]
@lukedeo if you are happy with fixes you can aprove my pull request :)

**Comment by lukedeo** [comment]
Merged @ntsvetanov! Thanks for working on this, great job :)
